export const SNAPSHOT_DATE = "25 Sep 2026";
export const REGION = "ap-southeast-1";

export const NAV_ITEMS = [
  "Overview",
  "Data",
  "Experiments",
  "Training",
  "Model review",
  "Serving",
  "Monitoring",
];

export const MODELS = [
  {
    id: "rf",
    name: "RF",
    fullName: "Random Forest",
    f1: 0.762453,
    accuracy: 0.776836,
    fpr: 0.028009,
    unit: "flow",
    fitRows: "30,000 flows",
    testRows: "22,544 flows",
    run: "w53s4k21lvg6",
    pipeline: "bigdata-ids-dev-train",
    package: "bigdata-ids-dev-rf/4",
    approval: "Approved",
    endpoint: "bigdata-ids-dev-rf",
    input: "One raw 41-field NSL-KDD flow",
  },
  {
    id: "svm",
    name: "SVM",
    fullName: "Support Vector Machine",
    f1: 0.706118,
    accuracy: 0.726623,
    fpr: 0.075584,
    unit: "flow",
    fitRows: "8,000 flows",
    testRows: "22,544 flows",
    run: "bao44h4fqvdk",
    pipeline: "bigdata-ids-dev-train",
    package: "bigdata-ids-dev-classical/4",
    approval: "Approved",
    endpoint: null,
    input: "One raw 41-field NSL-KDD flow",
  },
  {
    id: "xgboost",
    name: "XGBoost",
    fullName: "Extreme Gradient Boosting",
    f1: 0.770881,
    accuracy: 0.783046,
    fpr: 0.029451,
    unit: "flow",
    fitRows: "30,000 flows",
    testRows: "22,544 flows",
    run: "4ixfq9dbl2vq",
    pipeline: "bigdata-ids-dev-xgboost",
    package: "bigdata-ids-dev-xgboost/1",
    approval: "Approved",
    endpoint: "bigdata-ids-dev-xgboost",
    input: "One raw 41-field NSL-KDD flow",
  },
  {
    id: "lstm",
    name: "LSTM",
    fullName: "Long Short-Term Memory",
    f1: 0.71854,
    accuracy: 0.740018,
    fpr: 0.057377,
    unit: "20-flow window",
    fitRows: "40,000 flows → 2,000 windows",
    testRows: "1,127 windows",
    run: "yjxa2d63nyic",
    pipeline: "bigdata-ids-dev-lstm",
    package: "bigdata-ids-dev-lstm/1",
    approval: "Approved",
    endpoint: "bigdata-ids-dev-lstm",
    input: "One preprocessed 20 × 25 tensor",
  },
];

export const LOCAL_MODELS = [
  { name: "Random Forest", unit: "flow", artifact: "random_forest.pkl" },
  { name: "SVM", unit: "flow", artifact: "svm.pkl" },
  { name: "LSTM", unit: "20-row window", artifact: "lstm.h5" },
  { name: "Autoencoder", unit: "flow", artifact: "autoencoder.h5" },
  { name: "XGBoost", unit: "flow", artifact: "xgboost.pkl" },
];

export const STAGE_GUIDANCE = {
  Overview: {
    eyebrow: "MODEL REVIEW",
    intro: "Check evidence before a model can serve predictions. The recorded AWS view is a historical snapshot.",
    shows: ["Four recorded AWS model results", "Official-test performance and release state", "A separate analytics branch"],
    checks: ["Official test and evaluation unit", "Model artifact and package version", "Input contract and endpoint target"],
    next: "Review the pending SVM package before any approval or deployment.",
    button: "Review model evidence",
    destination: "Model review",
  },
  Data: {
    eyebrow: "DATA",
    intro: "Understand which data feeds model training and which data is available for analytics.",
    shows: ["Raw NSL-KDD files in S3", "Separate Glue and Athena analytics branch", "UNSW-NB15 analytics dataset"],
    checks: ["Dataset identity and manifest", "Training vs official-test files", "Last successful ETL and query"],
    next: "Review the recorded training paths that consume raw NSL-KDD files.",
    button: "Explore training paths",
    destination: "Training",
  },
  Experiments: {
    eyebrow: "LOCAL EXPERIMENTS",
    intro: "The local five-model experiment is separate from the AWS deployment record.",
    shows: ["Five local model implementations", "Local processed arrays and MLflow intent", "Current driver limitation"],
    checks: ["Local split and preprocessing", "LSTM first-row window labels", "Run output before citing metrics"],
    next: "Use the AWS Training tab for recorded cloud runs.",
    button: "View AWS training",
    destination: "Training",
  },
  Training: {
    eyebrow: "TRAINING",
    intro: "Classical models and LSTM take two distinct SageMaker Processing paths.",
    shows: ["Three deployed AWS pipelines", "Recorded execution identifiers", "Different preprocessing and evaluation units"],
    checks: ["Model and parameter choice", "Processing cost before starting", "Execution status and failure reason"],
    next: "Start a new run only after reviewing the target pipeline and expected compute.",
    button: "Start training",
    action: "training",
  },
  "Model review": {
    eyebrow: "MODEL REVIEW",
    intro: "Approve a specific package only after its evaluation and input contract are checked.",
    shows: ["Approved package versions", "A pending SVM v5 package", "Official-test evaluation evidence"],
    checks: ["Exact package version", "F1, FPR and evaluation unit", "Model artifact and input contract"],
    next: "Review the pending SVM package. Approval does not deploy it.",
    button: "Review pending package",
    action: "approval",
  },
  Serving: {
    eyebrow: "SERVING",
    intro: "A model package and a serving endpoint are separate resources.",
    shows: ["Three recorded Serverless endpoints", "SVM has no dedicated endpoint", "Different classical and LSTM request formats"],
    checks: ["Approved package and candidate name", "Memory and concurrency", "Smoke test and rollback plan"],
    next: "Create a candidate endpoint only after package review.",
    button: "Review deployment",
    action: "deployment",
  },
  Monitoring: {
    eyebrow: "MONITORING",
    intro: "The recorded PSI alarm was exercised with synthetic data; monitoring is not scheduled.",
    shows: ["Three recorded PSI examples", "CloudWatch alarm threshold", "Missing-data handling"],
    checks: ["Last metric observation time", "Whether a shift was synthetic", "Baseline and source schema"],
    next: "Inspect the recorded drift report and current CloudWatch datapoint before acting.",
    button: "Review drift evidence",
    destination: "Monitoring",
  },
};

export const GITHUB_WORKFLOW = "https://github.com/galaxyofmind/ml-ids-zero-trust-cloud/actions/workflows/aws-train.yml";
export const SAGEMAKER_CONSOLE = `https://${REGION}.console.aws.amazon.com/sagemaker/home?region=${REGION}#/pipelines`;
export const CLOUDWATCH_CONSOLE = `https://${REGION}.console.aws.amazon.com/cloudwatch/home?region=${REGION}#alarmsV2:`;
